name: Build & Deploy FutStats

on:
  push:
    branches:
      - main

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18"

      - name: Install dependencies
        run: npm ci

      - name: Build Angular app
        run: npm run build --if-present

      - name: Install Firebase CLI
        run: npm install -g firebase-tools

      - name: Deploy Firestore sync function
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_ADMIN_SDK }}
        run: |
          firebase deploy --only functions:syncMatches --token "$FIREBASE_TOKEN"

      - name: Deploy Hosting
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_ADMIN_SDK }}
        run: |
          firebase deploy --only hosting --token "$FIREBASE_TOKEN"
